sudo: required
language: c
services:
- docker
env:
  global:
    - PROJECT_UUID=0572314c-bd21-11e9-8c83-024f4387ee42
    - secure: WzCjbxNd38QMwE32/zvMbmxohkbofP2JaevG3++ICqXJavnDopj6wNRBVgdWD9FEAF7OaxFbhVIlOnB30MuLucsepiEjGUR72c+KM92x/wRf4VguGwTjN0/hvrT00nHp8z2YzkuCn2atXyfORbNQvt7zWy7nsi/UmztXr9o3hZ3OfJ+08KQi+DPeoZ/5bSI3IDhHY1L4pHNNv5ehDG/UPw/j1FUhELcQhs2vpshHrWk8FKx3+g/uDls5SkIp12VJ99/0VOFsdRAIHAQ+4bPvrvL3XvgsDXRBiCE3IyG84PoeXLFyrSjv8kszAJ6VYfaruneKn9Pl4QHKMARK5WIQuX2YJL62SirtYr3fD89L4MwbBWP3EXb3dNLN6zD5xKz7WfcDusP7m1glT048ojxztTrEN7NevTvOhqxKM/OKLzdrmvK7/gyuO+RvnhWd5PZiRbusMTE6H/BS9wMWZ0HDJ9l5RDQ1999HxkVlfXU4ITDIPomml/W0qnGnvfDW9eQ9QDbWwFIbs3HI82AJuesY/0gfJpW/FuKmd5SFMbN9ZltPE6V6jmoM+0g851u6jl+5tb9XIGD3fFMetDrpJMIygL4JnMuelZmzPXVJGGBUUWGdLv33FbzqGztkN9ZCSZ8tPy3ATEPaI64waJ7Zqm4pCOsHMknl2W7X4wylY3TysQ0=
before_script:
- sudo apt-get install -y musl
- wget https://download.pltcloud.com/cli/pltcloud_0.2.1_amd64.deb
- sudo dpkg -i pltcloud_0.2.1_amd64.deb
script:
- make docker
deploy:
  - provider: script
    script: make deploy
    on:
      all_branches: true
    #  branch: develop
notifications:
  slack:
    secure: GgjfEaZ2DpRNDNgG0u+JlSwwU5GGFpfBL4ExsRYvCo+N5Q0d3vmIqj1sQtoXWn6L9++pyEL19D8D+Rvtx3P+WHIDvRN/Qaj991+iOwWsjmWYx91UdjpTQx+Evjlem9+ekRI8/PsbruspkpAr3l2n3yzhndP5aa7L2kGA7sEp3x3qcNaU+eQUcuIsv7TmwahEsKX0BWqOm34e2ESlUBoqOYyn24cVceKukuaetf20WpRQR8JKGpQnFWeXqHugLmw8mjE8LCdMqbPCDXssfKxrzxixMUPDyU14XD8FAVLlSBUwj50j5P+FQd5wvjoALDIbozyW5r9I1MiGGcFfaBDc57uJAdKHJGeupdri2xXXCqvU4ROdDyRqr+kCcL0ypEsjtTZolxvPc3oqoihkhiIg1W7ud/95JmD7pkJfuO1LbSZFn5EF2+KajW5ewpzuElKvq5axEgVXZNYFXliAThdVzs5qYPU2vkpmWu8lpjKgW90jzaP6H/8UqRI0UocdSF2D6Buen0FysesHNKLDIW1113DRF9Y//lwQTDjuRVbYS8WzGDrsTOs/Jren3CXTqJ2ykgoJ7oEGuRzbtCdS41KYF4+ot4i1ZqUunRlkPNaWGPfZDvQForuxfEvbIPFOejW9rVY9qW1YFjyL0BaiyjKtBFRsIYZaq3P0WOdrdeu+mfc=
